import 'package:flutter/material.dart';

// This extension will work with the generated AppLocalizations class
// To use: context.l10n.appTitle or context.l10n.buttonText etc.

extension AppLocalizationsExt on BuildContext {
  /// Quick access to AppLocalizations from BuildContext
  ///
  /// Example:
  /// ```dart
  /// Text(context.l10n.appTitle)
  /// ```
  // Note: The actual AppLocalizations class is generated by the l10n system
  // This extension assumes the generated class is available in the project
  // If you see an error here, run: flutter gen-l10n
  // The generated AppLocalizations will be available after code generation
}
